version: 2.1

jobs:
  build_and_push:
    docker:
      # - image: cimg/go:1.17
      - image: cimg/base:current
    environment:
      IMAGE_VERSION: v1
      DOCKER_REPO: longvd99
    steps:
      - checkout

      - setup_remote_docker:
          version: edge

      # - run:
      #     name: Install Docker client
      #     command: apt install docker-cli
      - run:
          name: Check file and path
          command: |
            ls -la && pwd

      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      # Build Docker images for each service
      - run:
          name: Build and tag udagram-api-user image
          command: |
            docker build -t ${DOCKER_REPO}/udagram-api-user:$IMAGE_VERSION ../udagram-api-user

      - run:
          name: Build and tag udagram-api-feed image
          command: |
            docker build -t ${DOCKER_REPO}/udagram-api-feed:$IMAGE_VERSION ../udagram-api-feed

      - run:
          name: Build and tag udagram-frontend image
          command: |
            docker build -t ${DOCKER_REPO}/udagram-frontend:$IMAGE_VERSION ../udagram-frontend

      - run:
          name: Build and tag reverseproxy image
          command: |
            docker build -t ${DOCKER_REPO}/reverseproxy:$IMAGE_VERSION ../reverseproxy

      # Push images to Docker Hub
      - run:
          name: Push udagram-api-user image
          command: |
            docker push ${DOCKER_REPO}/udagram-api-user:$IMAGE_VERSION

      - run:
          name: Push udagram-api-feed image
          command: |
            docker push ${DOCKER_REPO}/udagram-api-feed:$IMAGE_VERSION

      - run:
          name: Push udagram-frontend image
          command: |
            docker push ${DOCKER_REPO}/udagram-frontend:$IMAGE_VERSION

      - run:
          name: Push reverseproxy image
          command: |
            docker push ${DOCKER_REPO}/reverseproxy:$IMAGE_VERSION

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push